### ISSUE TITLE
how to encrypt webm files

### ISSUE THREAD

**Issue by bahaaEldeen1999** [SingingTree/Webm-EME-Examples#2]
can you please tell us how did you manage to clearkey encrypt your webm files and how did you get the key value and id ? thanks a lot for the examples

**Comment by SingingTree** [comment]
I'd suggest using [shaka-packager](https://github.com/google/shaka-packager). For clearkey you can just make up the key and id provided they fit the expected clearkey format.

Note, the files here may have been created using the [`webm_crypt` tool](https://github.com/webmproject/webm-tools/tree/master/webm_crypt), as they were made some years ago. However, I'd suggest using shaka these days.

**Comment by bahaaEldeen1999** [comment]
sir thank you so much your example code saved me from hundreds of lines of searching and trying to understand eme api , i used shaka and it worked, i will try to get deeper understanding of eme as well, thanks for your respons
